### ISSUE TITLE
Any guidance on where to find such rule mapper file?

### ISSUE THREAD

**Issue by jerrydeng** [IHTSDO/snomed-to-icd-10-mapper#1]
Can you give some direction on how to find such -rf2-map file?  I'm new to this field, do I find such mapper myself via SNOMED's downloads?

**Comment by kaicode** [comment]
The SNOMED-CT to ICD-10 Map is a type of [extended map](https://confluence.ihtsdotools.org/display/DOCRELFMT/5.2.3.3+Complex+and+Extended+Map+from+SNOMED+CT+Reference+Sets) with some rules and map groups to be aware of.

The map file can be found within the International Edition RF2 archive under Snapshot/Refset/Map/der2_iisssccRefset_ExtendedMapSnapshot_INT_*.txt

**Comment by kaicode** [comment]
Just let me know if there are any further questions on this.

**Comment by jerrydeng** [comment]
I was able to find it in SNOMED International Edition. Thanks
